### ISSUE TITLE
Add missing controllers

### ISSUE THREAD

**Issue by mteblesz** [mteblesz/servartur#4]
### Match-up:
- [x] create room
- [x] join room - replaced with _get room info_  (no changes to db, only need info for client)
- [x] add player
- [x] remove player
- [x] modify roles - client side only? then StartMatchDto( List<Role> roles) (check here for valid role pairings)
- [x] start game (assign roles, **assign player order** -> create first squad, assign leader, ->change state to <Playing>)
                          only for host (info about host from RoomInfo, or a Player.IsHost?) - Host info stored on front - two distinct 
                          pages (after CreateRoom, and JoinRoom button, first one with button to start game)
                          limit nuber of players in a room on serverside
- [x] get player info (role) after game started

### Squad choice
- [x] get memberCounts info for quests(for quest numbers)  (for display info and for submit validation) / would be stored in clients cache or smth - no need - squad has field for it
- [x] add member
- [x] remove member
- [ ] submit squad - with members info in dto (only for leader - infor from squad)
- [ ] vote squad 

### Quest:
- [ ] vote quest
- [ ] get game result info after 5 quests are done

### Assassination
- [x] get evil players list(with roles) for everyone
- [x] get good players list for assassin
- [ ] kill a good player

### Other:
- [ ] view history of matches
- [x] view quest info after result

**Comment by mteblesz** [comment]
idk why closed it

**Comment by mteblesz** [comment]
# TODO of TODO
- [x] get player info (role) after game started

### Squad choice
- [x] get memberCounts info for quests(for quest numbers)  (for display info and for submit validation) / would be stored in clients cache or smth - no need - squad has field for it
- [x] add member
- [x] remove member
- [x] submit squad - with members info in dto (only for leader - infor from squad)
- [x] vote squad 

### Quest:
- [x] vote quest
- [x] get game result info after 5 quests are done

### Assassination
- [x] get evil players list(with roles) for everyone
- [x] get good players list for assassin
- [x] kill a good player


### Other:
- [ ] view history of matches
- [x] view quest info after result
